[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "edwh-locust-plugin"
description = 'locust project with a plugin to be discovered from the edwh package'
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
  { name = "Remco Boerma", email = "remco.b@educationwarehouse.nl" },
  { name = "Robin van der Noord", email = "robin.vdn@educationwarehouse.nl" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = ['invoke']
version = "0.1.2"

[project.optional-dependencies]
dev = [
    "black",
]

[project.urls]
Documentation = "https://github.com/educationwarehouse/edwh-locust-plugin#readme"
Issues = "https://github.com/educationwarehouse/edwh-locust-plugin/issues"
Source = "https://github.com/educationwarehouse/edwh-locust-plugin"

# https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/#using-package-metadata
[project.entry-points."edwh.tasks"]
locust = "edwh_locust_plugin.locust_plugin"

[tool.vommit]
allow_breaking_bang = true
allow_breaking_footer = true
prerelease_token = "beta"
confirm = true
ignore = []

[tool.vommit.git]
enabled = true
origin = "origin"
branch = "master"
on_wrong_branch = "error"
tag_format = "v{version}"
commit_format = "{version}"

[tool.vommit.changelog]
enabled = true
file = "CHANGELOG.md"
include_prereleases = false
placeholder = "<!--next-version-placeholder-->"
placeholder_regex = "<auto>"
entry_title_format = "## v{version} ({date:%Y-%m-%d})"

[tool.vommit.changelog.levels]
feat = "Feature{s}"
fix = "Fix{es}"
break = "Breaking Change{s}"
docs = "Documentation"
perf = "Performance"

[tool.vommit.pypi]
enabled = true
use_keyring = true

[tool.vommit.commands]
clean = "rm -rf ./dist"
build = "uv build"
publish = "uv publish"
post_publish = ""

[tool.vommit.version_bump_map]
break = "major"
build = "patch"
chore = "patch"
feat = "minor"
fix = "patch"
perf = "patch"
refactor = "patch"

[tool.black]
target-version = ["py37"]
line-length = 120

[tool.ruff]
target-version = "py37"
line-length = 120

[tool.ruff.lint]
select = [
  "A",
  "ARG",
  "B",
  "C",
  "DTZ",
  "E",
  "EM",
  "F",
  "FBT",
  "I",
  "ICN",
  "ISC",
  "N",
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  "Q",
  "RUF",
  "S",
  "T",
  "TID",
  "UP",
  "W",
  "YTT",
]
ignore = [
  # Allow non-abstract empty methods in abstract base classes
  "B027",
  # Allow boolean positional values in function calls, like `dict.get(... True)`
  "FBT003",
  # Ignore checks for possible passwords
  "S105", "S106", "S107",
  # Ignore complexity
  "C901", "PLR0911", "PLR0912", "PLR0913", "PLR0915",
]
unfixable = [
  # Don't touch unused imports
  "F401",
]

[tool.ruff.lint.isort]
known-first-party = ["edwh_locust_plugin"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.per-file-ignores]
# Tests can use magic values, assertions, and relative imports
"tests/**/*" = ["PLR2004", "S101", "TID252"]

[tool.coverage.run]
source_pkgs = ["edwh_locust_plugin", "tests"]
branch = true
parallel = true
omit = [
  "src/edwh_locust_plugin/__about__.py",
]

[tool.coverage.paths]
edwh_locust_plugin = ["src/edwh_locust_plugin", "*/edwh-locust-plugin/src/edwh_locust_plugin"]
tests = ["tests", "*/edwh-locust-plugin/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
